server:
  port: 8090

spring:
  application:
    name: security
    oauth2:
      resourceserver:
        jwt.issuer-uri: http://localhost:8080/auth/realms/security-api

  keycloak:
    realm: web-app
    auth-server-url: http://localhost:8080/auth/
    resource: web-app
    public-client: true